version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgresdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 124578
      POSTGRES_DB: Recipies
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 5s

  migrate:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "dotnet tool restore && dotnet restore && dotnet ef database update --no-build --context AppDbContext --connection 'Host=postgresdb;Port=5432;Database=Recipies;Username=postgres;Password=124578'"

  webapi:
    build: .
    container_name: RecipiesAPI
    env_file:
      - .env
    ports:
      - "5000:80"  # host:container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80  
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=Recipies;Username=postgres;Password=124578
    depends_on:
      - postgres
      - migrate
 

volumes:
  pgdata:
